package saurav.taskmaster.task.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "Task")
public class Task {
    private UUID id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String images;
    private String thumbImg;


    public Task(){}
    public Task(String title,String description){
        this.setTitle(title);
        this.setDescription(description);
        this.setStatus("Available");
        this.setAssignee("");
    }
    public Task(String title,String description,String assignee){
        this.setTitle(title);
        this.setDescription(description);
        this.setStatus("Assigned");
        this.setAssignee(assignee);
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    @DynamoDBAttribute
    public String getThumbImg() {
        return thumbImg;
    }

    public void setThumbImg(String thumbImg) {
        this.thumbImg = thumbImg;
    }
}
